# Generated by Django 6.0.7 on 2026-07-08 18:53

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SadaqahCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('raised_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('is_urgent', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='campaigns/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sadaqah_campaigns',
            },
        ),
        migrations.CreateModel(
            name='QardHasanLoan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('education', 'Education'), ('medical', 'Medical Emergency'), ('business', 'Small Business'), ('housing', 'Housing'), ('other', 'Other')], max_length=20)),
                ('purpose_detail', models.TextField()),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount_repaid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5)),
                ('repayment_months', models.PositiveSmallIntegerField(default=12)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('repaying', 'Repaying'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'qard_hasan_loans',
            },
        ),
        migrations.CreateModel(
            name='SadaqahDonation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('message', models.CharField(blank=True, max_length=300)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='islamic_finance.sadaqahcampaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sadaqah_donations',
            },
        ),
        migrations.CreateModel(
            name='ZakatRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cash_savings', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('gold_grams', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=8)),
                ('liabilities', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('nisab_used', models.DecimalField(decimal_places=2, max_digits=15)),
                ('zakat_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zakat_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'zakat_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
