# Generated by Django 6.0.7 on 2026-07-08 18:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('organization', models.CharField(blank=True, max_length=150)),
                ('amount', models.CharField(blank=True, max_length=50)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_applied', 'Not Applied'), ('applied', 'Applied'), ('in_review', 'In Review'), ('awarded', 'Awarded'), ('rejected', 'Rejected')], default='not_applied', max_length=15)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scholarships',
                'ordering': ['deadline', '-created_at'],
            },
        ),
    ]
