# Generated by Django 6.0.7 on 2026-07-08 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('riba', 'Riba (Interest/Usury)'), ('gharar', 'Gharar (Excessive Uncertainty)'), ('maysir', 'Maysir (Gambling)')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('keywords', models.TextField(help_text='Comma-separated keywords or phrases, matched case-insensitively.')),
                ('severity', models.CharField(choices=[('block', 'Block — reject the action entirely'), ('flag', 'Flag — allow but log for review')], default='flag', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('source_id', models.CharField(blank=True, max_length=64)),
                ('text_checked', models.TextField()),
                ('verdict', models.CharField(choices=[('compliant', 'Compliant'), ('flagged', 'Flagged'), ('blocked', 'Blocked')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_checks', to=settings.AUTH_USER_MODEL)),
                ('matched_rules', models.ManyToManyField(blank=True, related_name='matches', to='shariah_compliance.compliancerule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
