# Generated by Django 6.0.7 on 2026-07-08 18:53

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source', models.CharField(default='Monthly Allowance', max_length=100)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'allowances',
            },
        ),
        migrations.CreateModel(
            name='StudentExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('tuition', 'Tuition Fees'), ('hostel', 'Hostel/Accommodation'), ('food', 'Food & Feeding'), ('textbooks', 'Textbooks & Materials'), ('internet', 'Internet & Data'), ('research', 'Research & FYP'), ('certification', 'Certification Exams'), ('transport', 'Transport'), ('laptop', 'Laptop/Tech'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('budget', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_expenses',
                'ordering': ['-date'],
            },
        ),
    ]
