# Generated by Django 6.0.7 on 2026-07-08 18:53

import django.db.models.deletion
import transactions.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('transfer', 'Transfer'), ('airtime', 'Airtime'), ('data', 'Data Bundle'), ('zakat', 'Zakat'), ('sadaqah', 'Sadaqah'), ('qard', 'Qard Hasan'), ('bill', 'Bill Payment')], max_length=20)),
                ('category', models.CharField(choices=[('income', 'Income'), ('transfer', 'Transfer'), ('bills', 'Bills & Utilities'), ('food', 'Food & Dining'), ('transport', 'Transport'), ('education', 'Education'), ('housing', 'Housing'), ('health', 'Health'), ('shopping', 'Shopping'), ('zakat', 'Zakat'), ('sadaqah', 'Sadaqah'), ('qard', 'Qard Hasan'), ('student', 'Student Expense')], default='income', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('description', models.CharField(max_length=300)),
                ('reference', models.CharField(default=transactions.models.gen_ref, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='completed', max_length=10)),
                ('recipient_name', models.CharField(blank=True, max_length=150)),
                ('recipient_account', models.CharField(blank=True, max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
