# Generated by Django 6.0.7 on 2026-07-08 18:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(editable=False, max_length=16, unique=True)),
                ('cvv', models.CharField(editable=False, max_length=3)),
                ('expiry_date', models.DateField(editable=False)),
                ('cardholder_name', models.CharField(max_length=100)),
                ('is_frozen', models.BooleanField(default=False)),
                ('spending_limit', models.DecimalField(decimal_places=2, default=Decimal('200000.00'), max_digits=14)),
                ('amount_spent_this_period', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_card', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_transactions', to='cards.virtualcard')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
